-- 两人 App，无需 RLS，简化开发
ALTER TABLE profiles DISABLE ROW LEVEL SECURITY;
ALTER TABLE statuses DISABLE ROW LEVEL SECURITY;
ALTER TABLE daily_topics DISABLE ROW LEVEL SECURITY;
ALTER TABLE topic_answers DISABLE ROW LEVEL SECURITY;
ALTER TABLE wall_notes DISABLE ROW LEVEL SECURITY;
ALTER TABLE meet_plans DISABLE ROW LEVEL SECURITY;
ALTER TABLE meet_tasks DISABLE ROW LEVEL SECURITY;
ALTER TABLE math_problems DISABLE ROW LEVEL SECURITY;
ALTER TABLE math_formulas DISABLE ROW LEVEL SECURITY;
ALTER TABLE vocab_words DISABLE ROW LEVEL SECURITY;
ALTER TABLE vocab_progress DISABLE ROW LEVEL SECURITY;
ALTER TABLE vocab_quizzes DISABLE ROW LEVEL SECURITY;
