-- ============================================
-- 003_seed_vocab — 考研高频核心词汇
-- ============================================

INSERT INTO vocab_words (word, phonetic, meaning, example, list_number, frequency) VALUES
-- List 1: 高频核心
('abandon', '/əˈbændən/', 'v. 放弃；抛弃', 'He abandoned his plan to travel.', 1, 'high'),
('absorb', '/əbˈzɔːrb/', 'v. 吸收；吸引', 'Plants absorb sunlight for photosynthesis.', 1, 'high'),
('abstract', '/ˈæbstrækt/', 'adj. 抽象的 n. 摘要', 'The concept is too abstract to understand.', 1, 'high'),
('abundant', '/əˈbʌndənt/', 'adj. 丰富的，充裕的', 'The region has abundant natural resources.', 1, 'high'),
('accelerate', '/əkˈseləreɪt/', 'v. 加速，加快', 'The car accelerated smoothly.', 1, 'high'),
('access', '/ˈækses/', 'n. 通道；使用权 v. 访问', 'Students have access to the library.', 1, 'high'),
('accommodate', '/əˈkɒmədeɪt/', 'v. 容纳；提供住宿；适应', 'The hotel can accommodate 200 guests.', 1, 'high'),
('accompany', '/əˈkʌmpəni/', 'v. 陪伴；伴随', 'She accompanied me to the station.', 1, 'high'),
('accomplish', '/əˈkʌmplɪʃ/', 'v. 完成，实现', 'We accomplished our mission.', 1, 'high'),
('account', '/əˈkaʊnt/', 'n. 账户；描述 v. 解释', 'How do you account for the delay?', 1, 'high'),
('accumulate', '/əˈkjuːmjəleɪt/', 'v. 积累，积聚', 'Dust accumulated on the shelves.', 1, 'high'),
('accurate', '/ˈækjərət/', 'adj. 准确的，精确的', 'The weather forecast was accurate.', 1, 'high'),
('achieve', '/əˈtʃiːv/', 'v. 达到，取得', 'She achieved her goal of passing the exam.', 1, 'high'),
('acknowledge', '/əkˈnɒlɪdʒ/', 'v. 承认；感谢', 'He acknowledged his mistake.', 1, 'high'),
('acquire', '/əˈkwaɪər/', 'v. 获得；习得', 'She acquired a good knowledge of English.', 1, 'high'),
('adapt', '/əˈdæpt/', 'v. 适应；改编', 'You need to adapt to the new environment.', 1, 'high'),
('adequate', '/ˈædɪkwət/', 'adj. 充足的；适当的', 'The supply is not adequate for the demand.', 1, 'high'),
('adjust', '/əˈdʒʌst/', 'v. 调整，调节', 'Adjust the seat to a comfortable position.', 1, 'high'),
('administration', '/ədˌmɪnɪˈstreɪʃn/', 'n. 管理；行政', 'The administration decided to raise fees.', 1, 'high'),
('adopt', '/əˈdɒpt/', 'v. 采用；收养', 'We adopted a new approach to the problem.', 1, 'high'),
('advance', '/ədˈvɑːns/', 'v. 前进；推进 n. 进步', 'Technology has advanced rapidly.', 1, 'high'),
('adverse', '/ˈædvɜːs/', 'adj. 不利的；相反的', 'The drug has no adverse effects.', 1, 'high'),
('advocate', '/ˈædvəkeɪt/', 'v. 提倡，主张 n. 倡导者', 'He advocates a healthy lifestyle.', 1, 'high'),
('affect', '/əˈfekt/', 'v. 影响；打动', 'The weather affects crop growth.', 1, 'high'),
('aggregate', '/ˈæɡrɪɡət/', 'n. 总计 adj. 合计的', 'The aggregate score was 85.', 1, 'high'),
('allocate', '/ˈæləkeɪt/', 'v. 分配，拨出', 'Funds were allocated for the project.', 1, 'high'),
('alter', '/ˈɔːltər/', 'v. 改变，修改', 'Nothing can alter the fact.', 1, 'high'),
('alternative', '/ɔːlˈtɜːnətɪv/', 'n. 替代方案 adj. 替代的', 'We need to find an alternative solution.', 1, 'high'),
('ambiguous', '/æmˈbɪɡjuəs/', 'adj. 模棱两可的', 'The statement was deliberately ambiguous.', 1, 'high'),
('analyze', '/ˈænəlaɪz/', 'v. 分析', 'We need to analyze the data carefully.', 1, 'high'),
('annual', '/ˈænjuəl/', 'adj. 年度的，每年的', 'The annual report shows growth.', 1, 'high'),
('anticipate', '/ænˈtɪsɪpeɪt/', 'v. 预期；期望', 'We anticipate a large crowd.', 1, 'high'),
('apparent', '/əˈpærənt/', 'adj. 明显的；表面上的', 'The apparent cause was carelessness.', 1, 'high'),
('apply', '/əˈplaɪ/', 'v. 申请；应用', 'Apply the theory to practice.', 1, 'high'),
('appreciate', '/əˈpriːʃieɪt/', 'v. 欣赏；感激；升值', 'I appreciate your help.', 1, 'high'),
('approach', '/əˈproʊtʃ/', 'v. 接近 n. 方法', 'A new approach to learning English.', 1, 'high'),
('appropriate', '/əˈproʊpriət/', 'adj. 适当的 v. 拨款', 'Choose the appropriate tool for the job.', 1, 'high'),
('approximate', '/əˈprɒksɪmət/', 'adj. 大约的 v. 接近', 'The approximate cost is $100.', 1, 'high'),
('argue', '/ˈɑːrɡjuː/', 'v. 争论；论证', 'They argued about the plan for hours.', 1, 'high'),
('arise', '/əˈraɪz/', 'v. 出现，产生', 'Problems arose during the project.', 1, 'high'),

-- List 2: 高频核心
('aspect', '/ˈæspekt/', 'n. 方面；层面', 'Every aspect of the plan was considered.', 2, 'high'),
('assemble', '/əˈsembl/', 'v. 集合；组装', 'The team assembled in the conference room.', 2, 'high'),
('assess', '/əˈses/', 'v. 评估，评定', 'We need to assess the damage.', 2, 'high'),
('assign', '/əˈsaɪn/', 'v. 分配；指定', 'The teacher assigned homework to the class.', 2, 'high'),
('assist', '/əˈsɪst/', 'v. 帮助，协助', 'I will assist you with the project.', 2, 'high'),
('associate', '/əˈsoʊʃieɪt/', 'v. 联系；关联 n. 同事', 'People associate red with danger.', 2, 'high'),
('assume', '/əˈsjuːm/', 'v. 假定；承担', 'I assume you are right.', 2, 'high'),
('assure', '/əˈʃʊr/', 'v. 保证，使确信', 'I assure you of its quality.', 2, 'high'),
('attach', '/əˈtætʃ/', 'v. 附上；连接', 'Please attach the file to the email.', 2, 'high'),
('attain', '/əˈteɪn/', 'v. 达到，获得', 'He attained the rank of professor.', 2, 'high'),
('attempt', '/əˈtempt/', 'v. 尝试 n. 企图', 'She made an attempt to break the record.', 2, 'high'),
('attribute', '/əˈtrɪbjuːt/', 'v. 归因于 n. 属性', 'He attributes his success to hard work.', 2, 'high'),
('authority', '/ɔːˈθɒrəti/', 'n. 权威；当局', 'She is an authority on ancient history.', 2, 'high'),
('available', '/əˈveɪləbl/', 'adj. 可用的；有空的', 'Is the manager available?', 2, 'high'),
('aware', '/əˈwer/', 'adj. 意识到的，知道的', 'I am aware of the risks involved.', 2, 'high'),
('barrier', '/ˈbæriər/', 'n. 障碍；屏障', 'Language barriers can cause misunderstandings.', 2, 'high'),
('benefit', '/ˈbenɪfɪt/', 'n. 好处 v. 受益', 'Everyone will benefit from the new policy.', 2, 'high'),
('bias', '/ˈbaɪəs/', 'n. 偏见 v. 使有偏见', 'The study was free from bias.', 2, 'high'),
('bond', '/bɒnd/', 'n. 纽带；债券 v. 建立联系', 'The bond between mother and child.', 2, 'high'),
('brief', '/briːf/', 'adj. 简短的 n. 摘要', 'Give me a brief summary of the report.', 2, 'high'),
('capable', '/ˈkeɪpəbl/', 'adj. 有能力的', 'She is capable of handling the task alone.', 2, 'high'),
('capacity', '/kəˈpæsəti/', 'n. 能力；容量', 'The stadium has a capacity of 50,000.', 2, 'high'),
('capture', '/ˈkæptʃər/', 'v. 捕获；吸引', 'The film captures the beauty of nature.', 2, 'high'),
('category', '/ˈkætəɡɔːri/', 'n. 类别，范畴', 'This book falls into the fiction category.', 2, 'high'),
('challenge', '/ˈtʃælɪndʒ/', 'n. 挑战 v. 质疑', 'The challenge was accepted.', 2, 'high'),
('characteristic', '/ˌkærəktəˈrɪstɪk/', 'n. 特征 adj. 典型的', 'One characteristic of good leaders.', 2, 'high'),
('circumstance', '/ˈsɜːkəmstəns/', 'n. 环境；情况', 'Under the circumstances, I agree.', 2, 'high'),
('claim', '/kleɪm/', 'v. 声称；索取 n. 主张', 'He claims to have seen the suspect.', 2, 'high'),
('classify', '/ˈklæsɪfaɪ/', 'v. 分类，归类', 'The books are classified by subject.', 2, 'high'),
('collapse', '/kəˈlæps/', 'v. 倒塌；崩溃', 'The building collapsed in the earthquake.', 2, 'high'),
('combine', '/kəmˈbaɪn/', 'v. 结合，联合', 'Combine theory with practice.', 2, 'high'),
('commit', '/kəˈmɪt/', 'v. 犯（罪）；承诺；投入', 'He committed himself to the project.', 2, 'high'),
('communicate', '/kəˈmjuːnɪkeɪt/', 'v. 交流；传达', 'We communicate by email.', 2, 'high'),
('community', '/kəˈmjuːnəti/', 'n. 社区；群体', 'The local community supported the plan.', 2, 'high'),
('compensate', '/ˈkɒmpenseɪt/', 'v. 补偿，赔偿', 'The company compensated the workers.', 2, 'high'),
('compete', '/kəmˈpiːt/', 'v. 竞争，比赛', 'Several companies compete for the contract.', 2, 'high'),
('complex', '/ˈkɒmpleks/', 'adj. 复杂的 n. 综合体', 'The problem is extremely complex.', 2, 'high'),
('component', '/kəmˈpoʊnənt/', 'n. 组成部分，部件', 'Each component of the system is vital.', 2, 'high'),
('concentrate', '/ˈkɒnsntreɪt/', 'v. 集中；浓缩', 'Concentrate on your studies.', 2, 'high'),
('concept', '/ˈkɒnsept/', 'n. 概念，观念', 'The concept of freedom is universal.', 2, 'high'),

-- List 3: 高频核心
('conclude', '/kənˈkluːd/', 'v. 总结；结束', 'The meeting concluded at noon.', 3, 'high'),
('conduct', '/kənˈdʌkt/', 'v. 进行；指挥 n. 行为', 'The experiment was conducted carefully.', 3, 'high'),
('confirm', '/kənˈfɜːm/', 'v. 确认；证实', 'Please confirm your attendance.', 3, 'high'),
('conflict', '/ˈkɒnflɪkt/', 'n. 冲突 v. 矛盾', 'The two reports conflict with each other.', 3, 'high'),
('connect', '/kəˈnekt/', 'v. 连接；联系', 'The bridge connects the two cities.', 3, 'high'),
('conscious', '/ˈkɒnʃəs/', 'adj. 有意识的；清醒的', 'He was conscious of being watched.', 3, 'high'),
('consequence', '/ˈkɒnsɪkwəns/', 'n. 结果，后果', 'Think about the consequences.', 3, 'high'),
('consider', '/kənˈsɪdər/', 'v. 考虑；认为', 'Consider all the options before deciding.', 3, 'high'),
('consist', '/kənˈsɪst/', 'v. 由…组成；在于', 'The team consists of five members.', 3, 'high'),
('constant', '/ˈkɒnstənt/', 'adj. 持续的；不变的', 'The constant noise is annoying.', 3, 'high'),
('constitute', '/ˈkɒnstɪtjuːt/', 'v. 构成；设立', 'Twelve months constitute a year.', 3, 'high'),
('construct', '/kənˈstrʌkt/', 'v. 建造；构建', 'The bridge was constructed in 1920.', 3, 'high'),
('consume', '/kənˈsjuːm/', 'v. 消费；消耗', 'The fire consumed the building.', 3, 'high'),
('contact', '/ˈkɒntækt/', 'n. 联系 v. 接触', 'Stay in contact with your friends.', 3, 'high'),
('contain', '/kənˈteɪn/', 'v. 包含；控制', 'The box contains old photographs.', 3, 'high'),
('context', '/ˈkɒntekst/', 'n. 上下文；背景', 'You need to understand the context.', 3, 'high'),
('contract', '/ˈkɒntrækt/', 'n. 合同 v. 收缩', 'Sign the contract before starting work.', 3, 'high'),
('contrast', '/ˈkɒntrɑːst/', 'n. 对比；差异', 'There is a sharp contrast between them.', 3, 'high'),
('contribute', '/kənˈtrɪbjuːt/', 'v. 贡献；投稿', 'Everyone contributed to the success.', 3, 'high'),
('controversial', '/ˌkɒntrəˈvɜːʃl/', 'adj. 有争议的', 'The topic remains controversial.', 3, 'high'),
('convention', '/kənˈvenʃn/', 'n. 惯例；大会', 'It is a convention to shake hands.', 3, 'high'),
('convince', '/kənˈvɪns/', 'v. 说服，使信服', 'I convinced him to change his mind.', 3, 'high'),
('cooperate', '/koʊˈɒpəreɪt/', 'v. 合作', 'The two companies cooperate closely.', 3, 'high'),
('correspond', '/ˌkɒrəˈspɒnd/', 'v. 符合；通信', 'The results correspond with our predictions.', 3, 'high'),
('create', '/kriˈeɪt/', 'v. 创造；引起', 'She creates beautiful paintings.', 3, 'high'),
('crisis', '/ˈkraɪsɪs/', 'n. 危机', 'The financial crisis affected millions.', 3, 'high'),
('criterion', '/kraɪˈtɪəriən/', 'n. 标准，准则', 'What is your criterion for success?', 3, 'high'),
('crucial', '/ˈkruːʃl/', 'adj. 关键的，重要的', 'This decision is crucial for the future.', 3, 'high'),
('culture', '/ˈkʌltʃər/', 'n. 文化；培养', 'Different cultures have different customs.', 3, 'high'),
('debate', '/dɪˈbeɪt/', 'n. 辩论 v. 讨论', 'The issue is under debate.', 3, 'high'),
('decline', '/dɪˈklaɪn/', 'v. 下降；拒绝', 'The economy is in decline.', 3, 'high'),
('define', '/dɪˈfaɪn/', 'v. 下定义；界定', 'How do you define happiness?', 3, 'high'),
('demonstrate', '/ˈdemənstreɪt/', 'v. 展示；证明', 'He demonstrated the experiment to the class.', 3, 'high'),
('deny', '/dɪˈnaɪ/', 'v. 否认；拒绝', 'He denied all the accusations.', 3, 'high'),
('derive', '/dɪˈraɪv/', 'v. 源自；获得', 'The word derives from Latin.', 3, 'high'),
('design', '/dɪˈzaɪn/', 'v. 设计 n. 图案', 'The building was designed by a famous architect.', 3, 'high'),
('despite', '/dɪˈspaɪt/', 'prep. 尽管', 'Despite the rain, we went out.', 3, 'high'),
('detect', '/dɪˈtekt/', 'v. 发现；探测', 'The sensor detects movement.', 3, 'high'),
('determine', '/dɪˈtɜːmɪn/', 'v. 决定；确定', 'We need to determine the cause.', 3, 'high'),
('device', '/dɪˈvaɪs/', 'n. 设备，装置', 'A smartphone is a useful device.', 3, 'high')
ON CONFLICT DO NOTHING;
